name: CI/CD Pipeline for Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # CI Job - Build and Test
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          pytest --disable-warnings --maxfail=1

  # CD Job - Deploy to AWS Elastic Beanstalk
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Only deploy if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 1: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change to your AWS region

      # Step 3: Deploy to Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          zip -r deploy-package.zip .
          aws elasticbeanstalk create-application-version --application-name my-python-app --version-label ${{ github.sha }} --source-bundle S3Bucket="elasticbeanstalk-us-west-2-your-bucket-name",S3Key="deploy-package.zip"
          aws elasticbeanstalk update-environment --environment-name my-python-app-env --version-label ${{ github.sha }}

  # Monitoring Job (Optional)
  monitoring:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Monitor Deployment Health
        run: |
          aws elasticbeanstalk describe-environment-health --environment-name my-python-app-env --attribute-names Status
